[workspace]
members = [
    "lib/interaction",
    "lib/video_capture",
    "lib/template",
    "lib/zeroes",

    "sketches/schotter5",
    "sketches/d20220201",
    "sketches/prime-spiral",

    "projects/log_density",
    "projects/cube_flow",

    "learning/learn-wgpu",
]

exclude = [
    "assets"
]

resolver= "2"
