[workspace]
members = [
    "interaction",
    "template",
    "nature_of_code/vectors",
    "nature_of_code/force",
    "nature_of_code/intro",
    "nature_of_code/ecosystem_project",
    "generative_design/p1"
]

exclude = [
    "template",
    "tutorials/schotter1",
    "tutorials/schotter2",
    "tutorials/schotter3",
    "tutorials/schotter4",
    "tutorials/universe",
    "d20220119",
    "d20220121"
]

resolver= "2"