[workspace]
members = [
    "areas/interaction",
    "projects/video_capture",
    "areas/schotter5",
    "projects/log_density",
    "projects/cube_flow",
    "resources/learn-wgpu",
    "sketches/d20220201"
]

exclude = [
]

resolver= "2"