[workspace]
members = [
    "lib/interaction",
    "lib/video_capture",
    "sketches/schotter5",
    "projects/log_density",
    "projects/cube_flow",
    "learning/learn-wgpu",
    "sketches/d20220201"
]

exclude = [
]

resolver= "2"