[workspace]
members = [
    "tutorials/learn-wgpu",
    "fluid/cpu_v1",
    "d20220204",
    "boids"
]

exclude = [
    "interaction",
    "template",
    "nature_of_code/vectors",
    "nature_of_code/force",
    "nature_of_code/intro",
    "nature_of_code/ecosystem_project",
    "generative_design/p1",
    "d20220130",
    "d20220201",
    "template",
    "tutorials/schotter1",
    "tutorials/schotter2",
    "tutorials/schotter3",
    "tutorials/schotter4",
    "tutorials/universe",
    "d20220119",
    "d20220121",
]

resolver= "2"