[workspace]
members = [
    "template",
    "nature_of_code/vectors",
    "d20220119",
    "d20220121"
]

exclude = [
    "tutorials/schotter1",
    "tutorials/schotter2",
    "tutorials/schotter3",
    "tutorials/schotter4",
    "tutorials/universe",
]

resolver= "2"